services:
  mariadb:
    image: mariadb
    hostname: mariadb
    networks:
      - kleschnet
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - db-mariadb:/var/lib/mysql:rw
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootsecretpassword
      - MYSQL_DATABASE=kassa
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
  frankenphp:
    build: .
    hostname: frankenphp
    restart: unless-stopped
    networks:
      - kleschnet
    depends_on:
      - mariadb
    ports:
      - "80:80"
    volumes:
      - /etc/kassa/web:/app/public
volumes:
  db-mariadb:
networks:
  kleschnet:
